apiVersion: v1
kind: ReplicationController
metadata:
  name: digibank
spec:
  replicas: 15
  selector:
    app: digibank
  template:
    metadata:
      name: digibank
      labels:
        app: digibank
    spec:
      containers:
      - name: digibank
        image: phavi85/digibank
        ports:
        - containerPort: 80
